spring:
  datasource:
    username: root
    password: Lyj991010.
    url: jdbc:mysql://localhost/demo?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity